{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: skillswap-message-service
  labels:
    app: skillswap-message-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: skillswap-message-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
